# Generated by Django 3.2.12 on 2022-04-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopt_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptreviewcomment',
            options={'ordering': ['review_comment_no']},
        ),
    ]
