# Generated by Django 3.2.12 on 2022-04-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt_review', '0002_alter_adoptreviewcomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
