# Generated by Django 3.2.12 on 2022-03-25 13:00

from django.db import migrations, models
import django.db.models.deletion
import streetanimal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllSecurityCenter',
            fields=[
                ('center_name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('center_address', models.TextField()),
                ('center_call', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announce_no', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('kind_of_animal', models.CharField(max_length=18)),
                ('breed', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=30)),
                ('neutering', models.CharField(max_length=30)),
                ('info', models.TextField()),
                ('date_time_of_receipt', models.DateTimeField()),
                ('reason_for_rescue', models.TextField()),
                ('place_of_discovery', models.CharField(max_length=50)),
                ('period_of_announcement', models.DateField()),
                ('shelter', models.CharField(max_length=30)),
                ('person_in_charge', models.CharField(max_length=18)),
                ('significant', models.TextField()),
                ('center_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetanimal.allsecuritycenter')),
            ],
            options={
                'ordering': ['-announce_no'],
            },
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('animal_image_no', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='', validators=[streetanimal.models.validate_image])),
                ('announce_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announce_image', to='streetanimal.animal')),
            ],
            options={
                'ordering': ['-animal_image_no'],
            },
        ),
    ]
