<<<<<<< HEAD
# Generated by Django 3.2.12 on 2022-04-06 10:22
=======
# Generated by Django 3.2.12 on 2022-04-06 10:20
>>>>>>> 70d7ba5e734cfd7b4bb43a690f4594fa2b00a545

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_owner_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findownerboardcomment',
            name='find_board_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='find_owner_board.findownerboard'),
        ),
    ]
