# Generated by Django 3.2.12 on 2022-04-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_owner_board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='findownerboard',
            name='size',
        ),
    ]
