# Generated by Django 3.2.12 on 2022-04-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_owner_board', '0003_alter_findownerboardcomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findownerboard',
            name='find_time',
            field=models.DateTimeField(),
        ),
    ]
