# Generated by Django 3.2.12 on 2022-04-11 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost_pet_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lostpetboardcomment',
            options={'ordering': ['-lost_comment_no']},
        ),
    ]
