# Generated by Django 3.2.12 on 2022-04-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost_pet_board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostpetboard',
            name='size',
        ),
    ]
