# Generated by Django 3.2.12 on 2022-04-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_pet_board', '0002_alter_lostpetboardcomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpetboard',
            name='lost_time',
            field=models.DateTimeField(),
        ),
    ]
